applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: TEAM_NAME-ci-cd
      namespaces:
        - name: TEAM_NAME-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-dev
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-test
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-stage
          bindings: *binds
          operatorgroup: true

  # Sealed Secrets


  # Tekton Pipelines


  # Sonarqube


  # Grafana


  # Allure


  # Matomo

  # Zalenium