applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
      namespaces:
        - name: TEAM_NAME-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-dev
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-test
          bindings: *binds
          operatorgroup: true
        - name: TEAM_NAME-stage
          bindings: *binds
          operatorgroup: true

  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.7"
    values:
      deploymentStrategy:
        type: Recreate
      nexus:
        env:
        - name: install4jAddVmParams
          value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
        - name: NEXUS_SECURITY_RANDOMPASSWORD
          value: "false"
      includeRHRepositories: false
      service:
        name: nexus


  # Sealed Secrets


  # Tekton Pipelines


  # Sonarqube


  # Grafana


  # Allure


  # Matomo
